services:
  ntfy-adapter:
    image: ghcr.io/chr0nzz/ntfy-adapter:latest
    container_name: ntfy-adapter
    restart: unless-stopped
    environment:
      # Change to your NTFY ip:port or domain:port #
      - NTFY_URL=http://<YOUR_NTFY_IP>:<PORT>  
      ## Change to your local timezone ##
      - TZ=America/Toronto  
      ### Optional: Override Notification Expiry ###
      # - EXPIRY_MAX=24 #Default is 48 hours
      # - EXPIRY_HIGH=12 #Default is 24 hours
      # - EXPIRY_STANDARD=6 #Default is 12 hours
      #### Optional: Override Emoji ####
      # **uicode or *short_code* (https://openmoji.org/)
      # - EMOJI_MAX=**U0001F6A8
      # - EMOJI_HIGH=*yellow_circle*
      # - EMOJI_STANDARD=*green_circle*
    ports:
      - "5000:5000"
